### ISSUE TITLE
I'd like to get pretty-printed tables

### ISSUE THREAD

**Issue by zacharysyoung** [rsc/markdown#16]
I like my tables to look something like:

```none
| foo col | bar col | baz col |
| :------ | :-----: | ------: |
| 1       |    2    |       3 |
| a       |    b    |       c |
```

with each column's cells padded to fit the max width of that column and match the column's alignment.

I'll be doing a PR for this. Can mdfmt turn on the Table option in the parser by default, or with a flag?

**Comment by rsc** [comment]
Merged #17.
