### ISSUE TITLE
allow capital X in task list items

### ISSUE THREAD

**Issue by matloob** [rsc/markdown#2]
Here's a go program running goldmark and markdown on the following input: https://go.dev/play/p/fZRthH1dl4B
```
- [X] task list item
```
Which is rendered on github as:

- [X] task list item

Its output is:
```
markdown:
<ul>
<li>[X] task list item</li>
</ul>


goldmark:
<ul>
<li><input checked="" disabled="" type="checkbox" /> task list item</li>
</ul>

```

**Comment by rsc** [comment]
Test comment; ignore.
