### ISSUE TITLE
Recommended approach for adding <img> attributes?

### ISSUE THREAD

**Issue by penbinder** [rsc/markdown#21]
I want to add width, height and srcset attributes to generated \<img> tags.  

I can get close to accomplishing my goal by walking through the document and replacing [Image](https://pkg.go.dev/rsc.io/markdown#Image) inlines with [HTMLTag](https://pkg.go.dev/rsc.io/markdown#HTMLTag) inlines.  The one thing that I cannot do is [render Image.Inner as text](https://github.com/rsc/markdown/blob/6256c626ee9089a6b9491eeff6126b5373b44a56/link.go#L131-L134).

Is what I am trying to do an expected use case for this package?   

If the answer is yes, then I'll proceed ahead for now by assuming that the image inner text is plain text and update later when an appropriate feature is added.

If the answer is no, then I'll [parse the HTML output](https://pkg.go.dev/golang.org/x/net/html) to add the attributes.

**Comment by rsc** [comment]
For now walking the data structure is the best answer. Perhaps there will be more printing customization in the future. Note that when you are holding a *Image you can do

    markdown.Format(markdown.Text{Inline: []Inline{img}})

to get the HTML that markdown would generate. Then you can sub in the width and height wherever you like in the tag and then replace the Image with an HTMLTag as you were suggesting.

**Comment by penbinder** [comment]
Thank you for the tip on formatting inlines.  That works great.
