### ISSUE TITLE
Allow `?`, `!`, `.`, `,`, `:,` `*`, `_`, and `~` on the interior of a link

### ISSUE THREAD

**Issue by matloob** [rsc/markdown#5]
GFM allows `?`, `!`, `.`, `,`, `:,` `*`, `_`, and `~` on the interior of a link: https://github.github.com/gfm/#extended-autolink-path-validation

Here's a program that compares markdown and goldmark on the following input: https://go.dev/play/p/uLHnavChGYX

```https://web.site:8080/~matloob```

Which is rendered on github as 
https://web.site:8080/~matloob

The output of the program is 
```
markdown:
<p><a href="https://web.site">https://web.site</a>:8080/~matloob</p>


goldmark:
<p><a href="https://web.site:8080/~matloob">https://web.site:8080/~matloob</a></p>
```

**Comment by rsc** [comment]
I think this bug was specifically only colon. If you find others let me know.

**Comment by matloob** [comment]
It's also showing up with ~. Running the program again, I get

```
markdown:
<p><a href="https://web.site:8080/">https://web.site:8080/</a>~matloob</p>


goldmark:
<p><a href="https://web.site:8080/~matloob">https://web.site:8080/~matloob</a></p>

```
