### ISSUE TITLE
Autolink can't start immediately after `[`

### ISSUE THREAD

**Issue by matloob** [rsc/markdown#8]
From the [gfm spec](https://github.github.com/gfm/#autolinks-extension): 

> All such recognized autolinks can only come at the beginning of a line, after whitespace, or any of the delimiting characters *, _, ~, and (.

Here's a go program that runs markdown and goldmark on the following input: https://go.dev/play/p/kTjBshQ82iQ

```
[https://golang.org]
```
Rendered in github as 

[https://golang.org]

The output of the program is 

```
markdown:
<p>[<a href="https://golang.org%5D">https://golang.org]</a></p>


goldmark:
<p>[https://golang.org]</p>
```

**Comment by rsc** [comment]
The spec is full of lies:

| input | GitHub |
| - | - |
`xhttps://go.dev` | xhttps://go.dev
`0https://go.dev` | 0https://go.dev
`%https://go.dev` | %https://go.dev
`αhttps://go.dev` | αhttps://go.dev
`[https://go.dev` | [https://go.dev

It is pretty funny that you can have an autolink after a 0 or α or % but not [.

**Comment by rsc** [comment]
How many of these did you find? I am inclined to leave [https://go.dev] auto-linking.

**Comment by matloob** [comment]
I think I saw just one or two on the sample I looked at. I'm okay with leaving this as is

**Comment by rsc** [comment]
Please reopen if anything changes.
